# Generated by Django 6.0.6 on 2026-07-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_consultacontacto_delete_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultacontacto',
            name='asunto',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
